### ISSUE TITLE
Can't use a ref as root prop

### ISSUE THREAD

**Issue by seanogdev** [apertureless/vue-observable#1]
First off, finding this really useful, so thank you. 

However I've noticed I'm unable to pass in an element with a ref as the `root` prop in the `<intersect>` component.

The error I get is that `HTMLDivElement` is not of type Object. Is there any workaround I could use? I don't see any examples of that prop being used in the tests currently, so I'm a bit unsure on how to proceed.

**Comment by apertureless** [comment]
Hey @miralize 
thanks for this. I will check it out. Seems that theres a bug and that the prop should not be typed as Object.

**Comment by apertureless** [comment]
Should be fixed now!

**Comment by seanogdev** [comment]
Awesome thanks!
