### ISSUE TITLE
Mutation & Resize are not exported 

### ISSUE THREAD

**Issue by smithalan92** [apertureless/vue-observable#3]
The docs state that you should be able to use the mutation observer and resize observer as well, but it looks like those are not exported in the currently published version of the module ( 0.1.1 ) , Any chance a new release could be published from the current master as I see there was a PR on the 25th of March to expose them? https://github.com/apertureless/vue-observable/pull/2/files

**Comment by apertureless** [comment]
Hey @smithalan92 

thanks for pointing that out. Totally forgot to publish it to npm.

Changes are now released!
